all:

heap:
	gcc heap.c -Wall -Werror -o heap

memory-issues:
	gcc memory-issues.c -Wall -Werror -o memory-issues

vector:
	gcc vector.c -Wall -Werror -o vector

stack-only:
	gcc stack-only.c -Wall -Werror -o stack-only

clean:
	rm -f stack-only heap memory-issues vector stack-only
